theme: jekyll-theme-primer
url: "https://www.gbcbincalendars.co.uk"
title: "Gedling Borough Council Refuse Collection Calendars"
permalink: /:title
lang: en-GB
timezone: Europe/London
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
kramdown:
  syntax_highlighter: rouge
  input: GFM

exclude: 
  - API.md
  - build.js
  - CNAME
  - Gedling Borough Council Bin Collection API.postman_collection.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - test/
  - USAGE.md
  - worker.js
  - wrangler.toml

sass:
  style: compressed
  load_paths:
    - node_modules/

# Custom
gtm: 
  container_id: GTM-P3MHVNSB
  auth: J1DjljiZzoVaDdrd1ACJBw
  preview: env-3

collectionSearchUrl: "https://api.gbcbincalendars.co.uk?streetName="
gedlingRefuseSearchUrl: https://apps.gedling.gov.uk/refuse/search.aspx