theme: jekyll-theme-primer
url: "https://www.gbcbincalendars.co.uk"
title: "Gedling Borough Council Refuse Collection Calendars"
lang: en-GB
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: 
  - build.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - USAGE.md

sass:
  style: compressed
  load_paths:
    - node_modules/

# Custom
gtm: 
  container_id: GTM-P3MHVNSB
  auth: J1DjljiZzoVaDdrd1ACJBw
  preview: env-3

collectionSearchUrl: https://api.gbcbincalendars.co.uk?streetName=