theme: jekyll-theme-primer
url: "https://jamesmacwhite.github.io/gedling-borough-council-bin-calendars/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/gedling-borough-council-bin-calendars" # the subpath of your site, e.g. /blog
title: "Gedling Borough Council Refuse Collection Calendars" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-seo-tag

sass:
  style: compressed
